### ISSUE TITLE
Can't add server

### ISSUE THREAD

**Issue by mogelbrod** [BenjaminOddou/alfred-plex#1]
First of all I'd like to thank you for sharing this workflow - it looks really promising!

I tried it out just now and was able to get it running after first manually running `pip3 install chardet` (it was missing from my mac environment).

I tried adding my plex server by pasting the following XML URL:
```
https://10-1-1-2.{REDACTED}.plex.direct:32400/library/metadata/16348?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExtras=1&includeFields=1&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1&X-Plex-Token={REDACTED}
```
Which resulted in a native notification popping up confirming that the server had been added (including the correct server name).

Unfortunately subsequent usage doesn't seem to pick up on the newly added server, instead claiming that

> No plex media server detected

If I try to add the server again I get the same confirmation notification, but with no apparent changes.

The alfred debugger logs the following:
```
[10:37:31.700] ERROR: Plex[Run Script] Traceback (most recent call last):
  File "{REDACTED}/Alfred.alfredpreferences/workflows/user.workflow.25E2B625-8870-4DF2-A76A-38DC604CD9AD/config_add_delete.py", line 46, in <module>
    with open(servers_file_path, 'w') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '{REDACTED}/Library/Application Support/Alfred/Workflow Data/com.benjamino.plex/servers.json'
```

`~/Library/Application Support/Alfred/Workflow Data/com.benjamino.plex/` doesn't exist on my machine, so I'm guessing the script needs to create the directory first.

**Comment by BenjaminOddou** [comment]
Hey @mogelbrod ! Thank you for the feedback. Indeed I see multiple problems here:

> I tried it out just now and was able to get it running after first manually running `pip3 install chardet` (it was missing from my mac environment).

I will need to investigate more on that. `chardet` is not used directly in my script. I suspect that maybe the `python-plexapi` module can't use `charset_normalizer` dependency. What's your python version ? The minimum required python version is 3.7 actually (not 3.6 as mentioned in the docs).

![charset](https://user-images.githubusercontent.com/85166574/225875869-6c0e3041-e5c3-46d6-8b18-d8fbcaa797d8.png)

> Which resulted in a native notification popping up confirming that the server had been added (including the correct server name).
> 
> Unfortunately subsequent usage doesn't seem to pick up on the newly added server, instead claiming that
> 
> > No plex media server detected
> 
> If I try to add the server again I get the same confirmation notification, but with no apparent changes.

The first `Success` notification is called if the server is valid but it is not checking that servers data is actually written. I will postponed it after the data is actually written in the `servers.json` file.

> `~/Library/Application Support/Alfred/Workflow Data/com.benjamino.plex/` doesn't exist on my machine, so I'm guessing the script needs to create the directory first.

Interesting. I thought Alfred was creating automatically the `data_folder` when the workflow is installed (if the `bundle id` is present : `com.benjamino.plex`). I will correct that.

I am planning to release a `v1.1` really soon with new features. I'll integrate the fix.

**Comment by mogelbrod** [comment]
Appreciate the quick reply, looking forward to trying out v1.1!

I'm on Python 3.9.9.
