### ISSUE TITLE
"Error! Data can't be written in servers.json"

### ISSUE THREAD

**Issue by Tantumonium** [BenjaminOddou/alfred-plex#10]
**After installing the Workflow:**
1. I am able add my Plex account via either my User/Pass or Token
2. When the account is added, I get the "Success" notification.
3. I then get an Error notification stating "Data can't be written in servers.json".

**When I trigger the workflow again:**
1. I select "Plex Media Servers" option
2. It then displays "No Plex media server detected"
3. I then go back and select "Plex Accounts", and select my account from the menu.
4. I select "Sync" and get a Succes message "plex account informations were updated"
5. Immediate afterward, I again get the Error message "Data can't be written in servers.json"

- I tried both account setup methods (no change)
- I tried deleting and reinstalling the Alfred worflow (no change)
- I located the "servers.json" file and tried changing its permissions to 666 (no change)
- I ran "pip list" to ensure that my python3 installation contains PlexAPI (which it does)
- I also tried changing the Workflow Configuration > "Data Folder" location to 2 different locations (no change)

I'm at a loss here.

**Comment by BenjaminOddou** [comment]
Hello @Tantumonium, the error message is originating from [this section of the code](https://github.com/BenjaminOddou/alfred-plex/blob/main/src/accounts_add_delete.py#L18). Have you tried deleting the `servers.json` file? If that doesn't resolve the issue, could you try commenting out the `try/except` block to get more detailed logs?

**Comment by Tantumonium** [comment]
I have tried:

1. deleting the servers.json file and letting it be recreated, but got the same "Data can't be written" error.
2. commenting out the line "display_notification('🚨 Error !', 'Data can\'t be written in servers.json')" from "servers_add_delete.py"... which didn't help (I obviously didn't get the error, but no data was written into "servers.json")
3. I added an extra display notification to show the "e" error... but while "display_notification('🚨 Error !', 'Data can\'t be written in servers.json')" is shown, the new "display_notification('Error Msg: ', e)" is not.

Where is "custom_logger('error', e)" logging to? I also saw a "plex.log" listed in "utilities.py", but can't find it.

**Comment by BenjaminOddou** [comment]
What is the exact message you see in the Plex log for the error? Could you try logging the data to the Plex log by adding the line `custom_logger('test', data)` at the end of the except block? If possible, remove all personal information and share the result.

**Comment by Tantumonium** [comment]
BEFORE adding the line to log the "data" object... I selected Plex Accounts > [my account] > Sync ... and the plex.log says "2024-09-23 14:41:05,333 - ERROR - name 'data' is not defined".

AFTER adding the line to log the "data" object... nothing was logged at all when I tried to Sync.

NOTE:
Early today I decided to see if I could manually create the info needed in the servers.json file. I'm not really a programmer, so I had Google Gemini analyze  "servers_add_delete.py" and had it write a python script ( [getPlexServers.py.zip](https://github.com/user-attachments/files/17102882/getPlexServers.py.zip) ) to make a PlexAPI call and write the json data to the servers.json file... which worked great and I was able to use your Alfred Workflow as intended.

**Comment by BenjaminOddou** [comment]
@Tantumonium the bug should be resolved with new [2.3.0](https://github.com/BenjaminOddou/alfred-plex/releases/tag/v2.3.0) version. Could you tell me if it changes something on your side ?

**Comment by Tantumonium** [comment]
I did a fresh install of 2.3.0 on my alternate laptop, and everything works as expected! 

I'll try it again tomorrow on my primary laptop, which is where I have been experiencing this issue.

**Comment by BenjaminOddou** [comment]
@Tantumonium great ! I am closing the issue for now, don't hesitate to come back in case there is still a bug.
