### ISSUE TITLE
Suggestion: Add "Infuse" Media Player to players list (if possible)

### ISSUE THREAD

**Issue by Domingus** [BenjaminOddou/alfred-plex#12]
Hello Benjamin, greetings from germany!

i just installed your amazing Plex workflow into Alfred and i would like to suggest to add another media player to the players list, if possible : Infuse
https://apps.apple.com/de/app/infuse-video-player/id1136220934

The reason behind this: Infuse is currently the only video player that can play Videos with HDR correctly, and since I have a HDR capable TV, it would be nice if this player could make it on the list...
Another plus of Infuse is that it can be connected with trakt.tv.
So.... this is a pretty awesome Videoplayer and I can only hope that you consider supporting it in the future...

kind regards
Alex

**Comment by BenjaminOddou** [comment]
Hello Alex,

Thank you for reaching out and for your kind words about the Plex workflow! I’m glad you’re enjoying it.

Apologies for the late response—things have been a bit hectic on my end.

I really appreciate the suggestion to add Infuse to the list of supported players. It’s indeed a great video player, and I’ll look into updating the Alfred workflow very soon to incorporate Infuse.

However, please note that Infuse doesn’t accept standalone audio streams, so it won’t be possible to use it for audio streaming. It will only work for video playback.

Best regards,
Benjamin

**Comment by BenjaminOddou** [comment]
The new [2.4.0](https://github.com/BenjaminOddou/alfred-plex/releases/tag/v2.4.0) version now supports Infuse. Don't hesitate to give some feedbacks.
