### ISSUE TITLE
Plex Discover search not working

### ISSUE THREAD

**Issue by Resserene** [BenjaminOddou/alfred-plex#5]
Hi,
I get the following notification when performing a search in Discover - "Failed to connect to Plex Discover. Check the token".

When I first installed the workflow, Discover was disabled in my Plex account. Later I enabled it but still won't work in the workflow. 

I've tried reinstalling the workflow (also deleted the database folder for the workflow). I tried restarting Plex and getting the XML link again. Still won't work. 

Running v1.5 of the workflow with PMS v4.108.

**Comment by BenjaminOddou** [comment]
Hello,

Thanks for reporting this. Is the bug only restricted to discover search ? If this is the case could you use another token (from another browser) or remove the current client (browser) from your account and sign in again ? The token is coming from the XML link in the [X-Plex-Token](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/) property. Consider removing the server from the workflow as well (Plex Configuration from the menu).

If still not working, I would ask you to give me the error message that is coming from the plexapi. For that you can create a python script (let say `debug.py`) in the workflow directory with the following content:

```python
# replace plexToken with you actual X-Plex-Token
import sys
sys.path.insert(0, './lib')
from plexapi.myplex import MyPlexAccount

plex_account = MyPlexAccount(<plexToken>, timeout=600)
print(plex_account)
```

Open the terminal and type:

```shell
python3 /path/to/the/workflow_dir/debug.py
```

> You can drag and drop the file in the terminal window to get it’s url.

**Comment by Resserene** [comment]
Yes, I tried getting another token from a different browser. Also, removed the server from the workflow several times. Both not seem to be working. 

Is my token after the = in "1&X-Plex-Token="? And do I write the token between the <> as shown in plex_account = MyPlexAccount(<plexToken>, timeout=600)? Because I seem to be getting syntax errors in the Terminal.

**Comment by BenjaminOddou** [comment]
@Resserene thanks for the feedback. Yes your plexToken is right after the `=`. Don't keep `<` and `>` in the script.

**Comment by Resserene** [comment]
Yes, Discover is working as expected from the browser. 

I'm getting the following from the script -

`NameError: name <plexToken> is not defined`

**Comment by BenjaminOddou** [comment]
> Yes, Discover is working as expected from the browser. 
> 
> 
> 
> I'm getting the following from the script -
> 
> 
> 
> `NameError: name <plexToken> is not defined`

I think the plexToken is not input correctly in the script

Did you replace <plexToken> by "YourToken" in the script (with quotes ?). I can't ask you to give me the full code as plexToken should be kept secret but it should be pasted into the script as raw string. If you are still stuck could you please use this script ?

```python
# this file is used to perform tests. Should be placed in the root folder of the workflow. Make sure to have one server connected to the workflow

from plexapi import utils
from plexapi.myplex import MyPlexAccount
from utils import servers_file

data = servers_file()

obj = data['items'][0] # first server used
plexToken = obj.get('plexToken')

plex_account = MyPlexAccount(plexToken, timeout=600)
print(plex_account)
```

**Comment by Resserene** [comment]
I ran the previous script again but this time had the token in "". It gave me the following - 

`<MyPlexAccount:"Some random number":"My name">`

Is something like this expected? I removed the number and name because I'm not sure I should be sharing that in public. 

I then ran the second script you provided and got this - 

`Traceback (most recent call last):
  File "/Users/anshul/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.415C790E-F946-4299-80E7-1C1E07FBFE10/debug.py", line 10, in <module>
    plex_account = MyPlexAccount(plexToken, timeout=600)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/plexapi/myplex.py", line 97, in __init__
    data, initpath = self._signin(username, password, code, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/plexapi/myplex.py", line 107, in _signin
    data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/plexapi/myplex.py", line 188, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://plex.tv/users/sign_in.xml <?xml version="1.0" encoding="UTF-8"?> <errors>   <error>Invalid email, username, or password.</error> </errors> `

**Comment by BenjaminOddou** [comment]
@Resserene Are you the admin user of you plex media server ? There is a 401 error (Unauthorized) coming from the plexapi library.

**Comment by Resserene** [comment]
That’s weird. Yes, I’m the admin.

**Comment by BenjaminOddou** [comment]
@Resserene really weird indeed. If you're the admin it's quite complicated to understand. I can reproduce the error 401 with a non admin token.

**Comment by Resserene** [comment]
Let me know if there’s any other way I could help debug this. In any case, I want to thank you for making this available for us. It has quickly become one of my favourite workflows. The Discover search feature would’ve been the cherry on the cake if it worked for me.

**Comment by BenjaminOddou** [comment]
@Resserene I'll try to help the best I can with that. My guess is that the token used to access the server is not the same as the one used to access your account (don't really know why).
Could you try to use this script ?

```python
import sys
sys.path.append('./lib')
from plexapi.myplex import MyPlexAccount

plex_account = MyPlexAccount(username='yourmail@gmail.com', password='yourPassword', code=None) # code is OTP code if any
print(f'Auth Token : {plex_account.authenticationToken}')
for s in plex_account.resources():
    print(f'Server Name : {s.name}, Server Token : {s.accessToken}')
```

If `Auth Token` is not the same as `Server Token` then it will explain the 401 unauthorized.

**Comment by Resserene** [comment]
No, this is the only server I own from my account. 

I couldn't try the script you provided because I had to delete the workflow because of a different problem that I'll describe in a new Issue.

**Comment by BenjaminOddou** [comment]
Let's see in the next release then ! I'll keep this open for now m. Hope you'll be able to test it

**Comment by Resserene** [comment]
Absolutely, looking forward.

**Comment by nammminn2** [comment]
had the same issue as well

**Comment by BenjaminOddou** [comment]
@nammminn2 @Resserene v2.0.0 is out. Don't hesitate to make some feedbacks ! 😄

**Comment by Resserene** [comment]
Will take it for a spin soon and get back to you with my experience.
